source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.3.6'
# Use Puma as the app server
gem 'puma', '~> 3.11'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

if ENV['RUBY_AGENT_VERSION_STATE']=='release'
  if ENV['RUBY_AGENT_VERSION'] == 'latest'
    gem 'elastic-apm'
  else
    gem 'elastic-apm', "~> #{ENV['RUBY_AGENT_VERSION']}"
  end
else
  if File.exist?('/tmp/branch')
    gem 'elastic-apm', git: "https://github.com/#{ENV['RUBY_AGENT_REPO']}.git", branch: ENV['RUBY_AGENT_VERSION']
  else
    gem 'elastic-apm', git: "https://github.com/#{ENV['RUBY_AGENT_REPO']}.git", ref: ENV['RUBY_AGENT_VERSION']
  end
end
