exporter = "otlp"
processor = "simple"

[exporters.otlp]
host = "apm-server"
port = 8200
scheme = "http"

[processors.batch]
max_queue_size = 2048
schedule_delay_millis = 5000
max_export_batch_size = 512

[service]
name = "nginx-proxy"
