xpack.fleet.packages:
    - name: system
      version: latest
    - name: elastic_agent
      version: latest
    - name: apm
      version: latest
    - name: fleet_server
      version: latest

xpack.fleet.agentPolicies:
    - name: Fleet Server + APM policy
      id: fleet-server-apm-policy
      description: Fleet server policy with APM and System logs and metrics enabled
      namespace: default
      is_default_fleet_server: true
      is_managed: false
      monitoring_enabled:
          - logs
          - metrics
      package_policies:
          - name: system-1
            id: default-system
            package:
                name: system
          - name: apm-1
            id: default-apm
            package:
                name: apm
            inputs:
              - type: apm
                keep_enabled: true
                vars:
                    - name: host
                      value: 0.0.0.0:8200
                      frozen: true
                    - name: url
                      value: http://apm-server:8200
                      frozen: true
          - name: Fleet Server
            package:
                name: fleet_server
            inputs:
                - type: fleet-server
                  keep_enabled: true
                  vars:
                      - name: host
                        value: 0.0.0.0
                        frozen: true
                      - name: port
                        value: 8220
                        frozen: true
