output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

heartbeat.monitors:
- type: icmp
  schedule: '*/5 * * * * * *'
  hosts: ["google.com"]
- type: tcp
  schedule: '@every 5s'
  hosts: ["myhost:7"]  # default TCP Echo Protocol
  check.send: "Check"
  check.receive: "Check"
- type: http
  schedule: '@every 5s'
  urls: ["https://www.elastic.co/"]
  check.response.status: 200
heartbeat.scheduler:
  limit: 10