---
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS:elasticsearch:9200}"]

setup.kibana:
  host: "${KIBANA_HOST:kibana:5601}"

processors:
  - add_observer_metadata:

heartbeat.monitors:
  - type: icmp
    schedule: '*/5 * * * * * *'
    hosts: ["google.com"]
  - type: tcp
    schedule: '@every 5s'
    hosts: ["myhost:7"]  # default TCP Echo Protocol
    check.send: "Check"
    check.receive: "Check"
  - type: http
    schedule: '@every 5s'
    urls: ["https://www.elastic.co/"]
    check.response.status: 200
heartbeat.scheduler:
  limit: 10

heartbeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: redis
          config:
            - type: tcp
              hosts: ["${data.host}:${data.port}"]
              schedule: "@every 1s"
              timeout: 1s
        - condition:
            contains:
              docker.container.image: opbeans
          config:
            - type: http
              urls: ["http://${data.host}:${data.port}"]
              schedule: "@every 5s"
              timeout: 1s

http.enabled: true
http.host: localhost
http.port: 5066
