#!/usr/bin/env bash
set -e

# .ci/scripts is added to $PATH by apm-pipeline-library
# so this script will be invoked by
# https://github.com/detailyang/pre-commit-shell, which
# is configured in .pre-commit-config.yaml.

docker run --rm -t -v "$PWD:/mnt" -u "$(id -u):$(id -g)" docker.elastic.co/observability-ci/shellcheck "$@"
