name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Run linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Lint
      run: .ci/scripts/lint.sh

  pre-commit:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: elastic/apm-pipeline-library/.github/actions/pre-commit@gh_actions

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
    - uses: actions/checkout@v3

    - name: test
      run: .ci/scripts/unit-tests.sh

    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: test-results
        path: tests/results/*junit.xml
